project:
  type: website

website:
  title: "Keira Rish | Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right:
      - href: https://github.com/KeiraRish?tab=repositories
        text: "<i class='bi bi-github'></i>"
        target: _blank
  search: false

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: false



